# Generated by Django 5.1.6 on 2026-05-12 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('week_start', models.DateField(verbose_name='начало недели')),
                ('week_end', models.DateField(verbose_name='конец недели')),
                ('is_published', models.BooleanField(default=False, verbose_name='опубликован')),
                ('max_participants', models.PositiveIntegerField(blank=True, help_text='Пусто — без лимита.', null=True, verbose_name='макс. участников')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quest_weeks_created', to=settings.AUTH_USER_MODEL, verbose_name='создал')),
            ],
            options={
                'verbose_name': 'неделя квестов',
                'verbose_name_plural': 'недели квестов',
                'ordering': ['-week_start', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QuestStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(db_index=True, verbose_name='порядок')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок')),
                ('description', models.TextField(blank=True, verbose_name='текст задания')),
                ('points', models.PositiveSmallIntegerField(default=1, verbose_name='очки')),
                ('related_cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quest_steps', to='cats.cat', verbose_name='кот из каталога')),
                ('quest_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='quests.questweek', verbose_name='неделя')),
            ],
            options={
                'verbose_name': 'шаг квеста',
                'verbose_name_plural': 'шаги квестов',
                'ordering': ['quest_week_id', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuestParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Активен'), ('completed', 'Завершён'), ('dropped', 'Брошен')], default='active', max_length=16, verbose_name='статус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_participations', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
                ('quest_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='quests.questweek', verbose_name='неделя')),
            ],
            options={
                'verbose_name': 'участие',
                'verbose_name_plural': 'участия',
            },
        ),
        migrations.CreateModel(
            name='QuestStepProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='выполнен')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='время выполнения')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='quests.questparticipation', verbose_name='участие')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_rows', to='quests.queststep', verbose_name='шаг')),
            ],
            options={
                'verbose_name': 'прогресс шага',
                'verbose_name_plural': 'прогресс шагов',
                'constraints': [models.UniqueConstraint(fields=('participation', 'step'), name='queststepprogress_unique_participation_step')],
            },
        ),
        migrations.AddConstraint(
            model_name='questweek',
            constraint=models.CheckConstraint(condition=models.Q(('week_end__gte', models.F('week_start'))), name='questweek_week_end_gte_week_start'),
        ),
        migrations.AddConstraint(
            model_name='questweek',
            constraint=models.CheckConstraint(condition=models.Q(('max_participants__isnull', True), ('max_participants__gte', 1), _connector='OR'), name='questweek_max_participants_null_or_positive'),
        ),
        migrations.AddConstraint(
            model_name='queststep',
            constraint=models.UniqueConstraint(fields=('quest_week', 'order'), name='queststep_unique_order_per_week'),
        ),
        migrations.AddConstraint(
            model_name='queststep',
            constraint=models.CheckConstraint(condition=models.Q(('points__gte', 1)), name='queststep_points_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='questparticipation',
            constraint=models.UniqueConstraint(fields=('user', 'quest_week'), name='questparticipation_unique_user_week'),
        ),
    ]
